#!/usr/bin/env python3
"""Deterministic MAP.md assembler for vibeassist-map (Phase 5).

Inputs (all produced by earlier phases):
  map/_stack.md     - REQUIRED. Phase 0 stack summary; becomes the header.
  map/_routes.json  - route list with path, audience, auth_required.
  map/_edges.json   - link edges: {"from": ..., "to": ..., "trigger": ...}.
                      Use "«global navigation»" (or "global") as `from` for chrome edges.
  map/pages/*.md    - page files named by the canonical slug.
  --machine-notes   - optional JSON {path: "what fetches this"} for the appendix.

Usage:
    python scripts/assemble.py map/ -o MAP.md [--machine-notes map/_machine_notes.json]
"""
import argparse
import json
import pathlib
import re
import sys
from collections import defaultdict

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

OP_TABLE = re.compile(r"\b(READS?|INSERT(?:/UPDATE)?|UPDATE|DELETE)\b[^`\n]*`(\w+)`")
PAGE_TITLE = re.compile(r"^#\s+(\S+)\s*[—-]?\s*(.*)$", re.M)


def route_slug(path: str) -> str:
    s = path.strip("/")
    s = re.sub(r"[:$\[\]]", "", s)
    return s.replace("/", "-") or "index"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map_dir")
    ap.add_argument("-o", "--out", default="MAP.md")
    ap.add_argument("--machine-notes", default=None)
    ap.add_argument("--harvest", default=None, help="map/_harvest.json - enables Findings, permissions, keys & services sections")
    args = ap.parse_args()
    mp = pathlib.Path(args.map_dir)

    stack_f = mp / "_stack.md"
    if not stack_f.is_file():
        sys.exit("ERROR: map/_stack.md is required (Phase 0 output). Write it first.")
    stack = stack_f.read_text(encoding="utf-8").strip()
    # _stack.md often opens with its own "# Stack" heading; we emit the wrapper, so strip theirs
    stack = re.sub(r"^#{1,6}\s*Stack\s*\n+", "", stack, count=1, flags=re.I)

    routes = json.loads((mp / "_routes.json").read_text(encoding="utf-8"))
    if isinstance(routes, dict):
        routes = routes.get("routes", [])
    edges = json.loads((mp / "_edges.json").read_text(encoding="utf-8")) if (mp / "_edges.json").is_file() else []
    if isinstance(edges, dict):
        edges = edges.get("edges", [])
    notes = json.loads(pathlib.Path(args.machine_notes).read_text(encoding="utf-8")) if args.machine_notes else {}
    harvest = json.loads(pathlib.Path(args.harvest).read_text(encoding="utf-8")) if args.harvest and pathlib.Path(args.harvest).is_file() else {}
    hmeta = harvest.get("_meta", {})

    user_routes = [r for r in routes if r.get("audience", "user") == "user"]
    machine_routes = [r for r in routes if r.get("audience") == "machine"]
    redirect_routes = [r for r in routes if r.get("audience") == "redirect"]

    pages_dir = mp / "pages"
    page_files = {}
    for r in user_routes:
        f = pages_dir / f"{route_slug(r['path'])}.md"
        if f.is_file():
            page_files[r["path"]] = f

    # --- edges indexed by source; global nav separated
    out_edges = defaultdict(list)
    global_targets = []
    for e in edges:
        src = e.get("from", "")
        if "global" in src.lower() or "«" in src:
            global_targets.append(e)
        else:
            out_edges[src].append(e)

    L = []
    L.append("# Application map — as a user meets it\n")
    L.append("_Generated by vibeassist-map. Regenerate with the scripts beside it; do not hand-edit._\n")

    # --- coverage table (counts read from data, never typed)
    L.append("## Coverage — read this before trusting anything below\n")
    L.append("| | |")
    L.append("| --- | --- |")
    L.append(f"| User-facing routes | **{len(user_routes)}** |")
    L.append(f"| Pages mapped in full | **{len(page_files)}** |")
    L.append(f"| Machine-only routes (appendix) | {len(machine_routes)} |")
    if redirect_routes:
        L.append(f"| Old addresses kept working (appendix) | {len(redirect_routes)} |")
    L.append(f"| Links traced | {len(edges)} |")
    missing = len(user_routes) - len(page_files)
    if missing:
        L.append(f"\n**{missing} user-facing routes are listed but not yet mapped.**")
    L.append("")

    # --- stack
    L.append("## Stack\n")
    L.append(stack + "\n")

    # --- global navigation, listed once
    if global_targets:
        L.append("## Global navigation (reachable from almost anywhere)\n")
        best = {}
        def rank(e):
            t = (e.get("trigger") or "").lower()
            return 0 if "redirect" in t else 1  # links beat redirects
        for e in global_targets:
            k = e.get("to", "?")
            if k not in best or rank(e) > rank(best[k]):
                best[k] = e
        for k in sorted(best):
            e = best[k]
            trig = f" — {e['trigger']}" if e.get("trigger") else ""
            L.append(f"- `{k}`{trig}")
        L.append("")

    # --- sitemap split public / signed-in
    L.append("## Sitemap\n")
    for title, group in (("Open to anyone", [r for r in user_routes if not r.get("auth_required")]),
                         ("Behind a sign-in", [r for r in user_routes if r.get("auth_required")])):
        if not group:
            continue
        L.append(f"### {title}\n")
        for r in sorted(group, key=lambda x: x["path"]):
            mark = " **← mapped**" if r["path"] in page_files else ""
            L.append(f"- `{r['path']}`{mark}")
            for e in sorted(out_edges.get(r["path"], []), key=lambda x: x.get("to", "")):
                trig = f" ({e['trigger']})" if e.get("trigger") else ""
                L.append(f"  - → `{e.get('to','?')}`{trig}")
        L.append("")

    # --- pages, in _routes.json (Phase 3) order
    L.append("---\n\n# Pages\n")
    tables = defaultdict(lambda: {"reads": set(), "writes": set()})
    for r in user_routes:
        f = page_files.get(r["path"])
        if not f:
            continue
        body = f.read_text(encoding="utf-8").strip()
        L.append(body + "\n\n---\n")
        # feed the data appendix from Evidence/READS lines
        for line in body.splitlines():
            if "Evidence:" not in line and "READS:" not in line:
                continue
            for op, table in OP_TABLE.findall(line):
                bucket = "reads" if op.upper().startswith("READ") else "writes"
                tables[table][bucket].add(r["path"])
                if op == "INSERT/UPDATE":
                    tables[table]["writes"].add(r["path"])

    # --- data appendix
    if tables:
        L.append("# Data appendix — each table, who reads it, who writes it\n")
        L.append("| Table | Read by | Written by |")
        L.append("| --- | --- | --- |")
        for t in sorted(tables):
            rd = ", ".join(f"`{p}`" for p in sorted(tables[t]["reads"])) or "—"
            wr = ", ".join(f"`{p}`" for p in sorted(tables[t]["writes"])) or "—"
            L.append(f"| `{t}` | {rd} | {wr} |")
        L.append("")

    # --- FINDINGS: things that look wrong (computed, then verified by the writer)
    if harvest:
        findings = []
        linked = {e.get("to") for e in edges}
        for r in user_routes:
            if r["path"] not in ("/",) and r["path"] not in linked and not r.get("not_found"):
                findings.append(f"**Nothing links to `{r['path']}`** — dead surface, unless it is reached from outside (check the page's own entry).")
        for t in hmeta.get("orphan_tables", []):
            findings.append(f"**Table `{t}` exists but no page touches it** — forgotten work, or accessed by something this map cannot see.")
        for t in hmeta.get("tables_without_rls", []):
            findings.append(f"**Table `{t}` has no row-level security enabled** — any signed-in client may be able to read or write it directly.")
        for r in user_routes:
            hv = harvest.get(r["path"], {})
            dng = hv.get("dangerous", [])
            if dng and not hv.get("has_confirm_pattern"):
                kinds = ", ".join(sorted({d["kind"] for d in dng}))
                findings.append(f"**`{r['path']}` can {kinds} — and no confirmation step was found.** One mis-tap is irreversible.")
        if findings:
            L.append("# Findings — things that look wrong\n")
            L.append("_Computed from the scan; each was verified against the code before publishing. If one is intentional, say so here rather than deleting it._\n")
            for x in findings:
                L.append(f"- {x}")
            L.append("")

    # --- who's allowed to do what
    if hmeta.get("rls_policies") or hmeta.get("rls_enabled"):
        L.append("# Who's allowed to do what (database rules)\n")
        by_table = defaultdict(list)
        for p in hmeta.get("rls_policies", []):
            by_table[p["table"]].append(p)
        for t in sorted(set(hmeta.get("rls_enabled", [])) | set(by_table)):
            L.append(f"### `{t}`")
            if t not in hmeta.get("rls_enabled", []):
                L.append("- ⚠ policies exist but row-level security is NOT enabled — the policies do nothing")
            for p in sorted(by_table.get(t, []), key=lambda x: x["action"]):
                L.append(f"- {p['action']}: \"{p['policy']}\" (applies to {p['roles']})")
            if not by_table.get(t):
                L.append("- row-level security enabled, no policies found — nobody can touch this table from the client")
            L.append("")

    # --- keys & services
    if hmeta.get("services") or hmeta.get("env_vars"):
        L.append("# Keys & services — what you need to run this app\n")
        for s in hmeta.get("services", []):
            L.append(f"- {s}")
        ev = hmeta.get("env_vars", {})
        if ev:
            L.append("\nEnvironment variables the code expects:\n")
            for name in sorted(ev):
                L.append(f"- `{name}` (first used {ev[name]['file']}:{ev[name]['line']})")
        L.append("")

    # --- redirect appendix
    if redirect_routes:
        L.append("# Old addresses that still work (you are sent onward)\n")
        for r in sorted(redirect_routes, key=lambda x: x["path"]):
            dest = r.get("redirect_to")
            note = notes.get(r["path"]) or (f"an old address, kept working — sends you to `{dest}`" if dest
                                            else "an old address, kept working — sends you onward")
            L.append(f"- `{r['path']}` — {note}")
        L.append("")

    # --- machine-only appendix
    if machine_routes:
        L.append("# Machine-only routes (no person opens these)\n")
        for r in sorted(machine_routes, key=lambda x: x["path"]):
            note = notes.get(r["path"], "(add a one-line note: what fetches this?)")
            L.append(f"- `{r['path']}` — {note}")
        L.append("")

    pathlib.Path(args.out).write_text("\n".join(L), encoding="utf-8")

    # --- ONBOARD.md: the takeover pack's cover page. The skill produces this
    # once as the day-one snapshot; the APP owns keeping it current after import.
    O = []
    O.append("# Read this first — taking over this app\n")
    O.append("_Day-one snapshot generated at import. The app maintains the living version; if this file looks stale, trust the app._\n")
    O.append("## What this is")
    O.append(stack + "\n")
    O.append("## State of the map")
    O.append(f"- {len(user_routes)} pages a person can open; {len(page_files)} mapped in full" + ("" if len(page_files) == len(user_routes) else f" — **{len(user_routes)-len(page_files)} still unmapped**"))
    O.append(f"- {len(tables)} database tables traced to the pages that touch them")
    if hmeta.get("data_layers"):
        O.append(f"- Talks to its database via: {', '.join(hmeta['data_layers'])}")
    O.append("")
    if harvest:
        nf = sum(1 for l in L if l.startswith("- **"))
        if nf:
            O.append("## Things that look wrong (verify before touching)")
            O.append(f"{nf} findings — dead surface, untouched tables, missing security rules, unconfirmed destructive actions. Full list in MAP.md under Findings.\n")
    if hmeta.get("services") or hmeta.get("env_vars"):
        O.append("## To run this app you need")
        for s in hmeta.get("services", []):
            O.append(f"- {s}")
        if hmeta.get("env_vars"):
            O.append(f"- {len(hmeta['env_vars'])} secret keys / environment variables (named in MAP.md under Keys & services)")
        O.append("")
    O.append("## Where to go next")
    O.append("- MAP.md — every page, what it does in plain language, and the evidence")
    O.append("- The data appendix in MAP.md — per table: who reads it, who writes it")
    O.append("- map/pages/ — one file per page if you only need one page's story")
    onboard = pathlib.Path(args.out).parent / "ONBOARD.md"
    onboard.write_text("\n".join(O), encoding="utf-8")
    nfind = sum(1 for l in L if l.startswith("- **"))
    print(f"assembled {args.out}: {len(page_files)}/{len(user_routes)} pages, "
          f"{len(tables)} tables in appendix, {len(machine_routes)} machine routes"
          + (f", {nfind} findings" if harvest else "") + " + ONBOARD.md")


if __name__ == "__main__":
    main()
